config/routes.rb
Rails.application.routes.draw do

# These routes set up both people and businesses for editing, and also adds 
# a nested resource for interactions. This allows us to easily create 
# interactions for both people and businesses.

  resources :people do 
    resources :interactions, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :businesses do
    resources :interactions, only: [:new, :create, :edit, :update, :destroy]
  end

  root to: "people#index"

end

app/models/business.rb
# == Schema Information
#
# Table name: businesses
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Business < ActiveRecord::Base

	has_many :interactions, as: :interactive, dependent: :destroy
	
end

app/models/interaction.rb
# == Schema Information
#
# Table name: interactions
#
#  id               :integer          not null, primary key
#  description      :string
#  interactive_id   :integer
#  interactive_type :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_interactions_on_interactive_type_and_interactive_id  (interactive_type,interactive_id)
#

class Interaction < ActiveRecord::Base

	belongs_to :interactive, polymorphic: true
	
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Person < ActiveRecord::Base

	has_many :interactions, as: :interactive, dependent: :destroy

	def name
	"#{first_name} #{last_name}"
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

    def index
      @businesses = Business.all
    end

    def show
      @business = Business.find(params[:id])
    end

    def new
      @business = Business.new
    end

    def create
      @business = Business.new(business_params)

      if @business.save
        redirect_to businesses_path, notice: "The business has been successfully created."
      end
    end

    def edit
      @business = Business.find(params[:id])
    end

    def update
      @business = Business.find(params[:id])
      if @business.update_attributes(business_params)
        redirect_to businesses_path, notice: "The business has been updated"
      end
    end

    def destroy
      @business = Business.find(params[:id])
      @business.destroy
      redirect_to businesses_path, notice: "The business has been deleted"
    end

    private

      def business_params
        params.require(:business).permit!
      end

end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController

	def new
		@context = context
		@interaction = @context.interactions.new
	end

	def create
		@context = context
		@interaction = @context.interactions.new(interaction_params)

		if @interaction.save
			redirect_to context_url(context), 
			notice: "The interaction has been successfully created."
		end
	end

	def edit
		@context = context
		@interaction = context.interactions.find(params[:id])
	end

	def update
		@context = context
		@interaction = @context.interactions.find(params[:id])
		if @interaction.update_attributes(interaction_params)
			redirect_to context_url(context), 
			notice: "The interaction has been updated"
		end
	end

	def destroy
		@context = context
		@interaction = context.interactions.find(params[:id])
		@interaction.destroy
		redirect_to context_url(context), 
		notice: "The interaction has been updated"
	end

	private

		def interaction_params
			params.require(:interaction).permit!
		end

		def context
			if params[:person_id]
				id = params[:person_id]
				Person.find(params[:person_id])
			else
				id = params[:business_id]
				Business.find(params[:business_id])
			end
		end 

		def context_url(context)
			if Person === context
				person_path(context)
			else
				business_path(context)
			end
		end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

  if @person.save
      redirect_to people_path, notice: "The person has been successfully created."
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(person_params)
      redirect_to people_path, notice: "The person has been updated"
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path, notice: "The person has been deleted"
  end

    private
    
      def person_params
        params.require(:person).permit!
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter the name of the business" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>
<%= render "form" %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>
<div class="well">
<%= link_to "New Business", new_business_path, class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Interactions</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @businesses.count == 0 %>
      <tr>
        <td colspan="3">
          No businesses found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @businesses.each do |business| %>
        <tr>
          <td><%= link_to business.name, business %></td>
          <td><%= business.interactions.count %></td>
          <td>
            <%= link_to "Edit", edit_business_path(business), class: "btn btn-default" %>

            <%= link_to "Delete", business_path(business),
            method: :delete,
            data: { confirm: "Are You Sure"},
            class: "btn btn-danger" %>

          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/businesses/new.html.erb
<h1>Create a New Business</h1>
<%= render "form" %>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>
<hr />
<h3>Interactions</h3>
<div class="well">
  <%= link_to "New Interaction", new_business_interaction_path(@business), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Interactive Type</th>
      <th>Created On</th>
      <th>Action</th>
    </tr>
  </thead>
  <% if @business.interactions.count > 0 %>
    <% @business.interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.description %></td>
        <td><%= interaction.interactive_type %></td>
        <td><%= time_ago_in_words interaction.created_at %> ago</td>
        <td>
        <%= link_to "Edit", edit_business_interaction_path(@business, interaction), 
        class:"btn btn-default" %>

        <%= link_to business_interaction_path(@business, interaction), 
            method: :delete, 
            data: { confirm: "You sure?" }, 
            class: "btn btn-primary" do %>
                Delete
        <% end %>

        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No interactions found for this business.  Click the 'New Interaction' button to create a new interaction.</td>
    </tr>
  <% end %>
</table>

app/views/interactions/_form.html.erb
<%= form_for [@context, @interaction] do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter a description of the interaction you had with this entity.", rows: 10 %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/interactions/edit.html.erb
<% if @context.class == Business %>

<h1>Editing Interaction for <%= @context.name %></h1>

<% else %>

<h1>Editing Interaction for <%= @context.first_name %></h1>

<% end %>

<%= render "form" %>

app/views/interactions/new.html.erb
<% if @context.class == Business %>

<h1>Editing Interaction for <%= @context.name %></h1>

<% else %>

<h1>Editing Interaction for <%= @context.first_name %></h1>

<% end %>

<%= render "form" %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('favicon.ico'), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="app-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>">
          <%= link_to "Home", root_path %>
        </li>
        <li class="<%= 'active' if current_page?(people_path) %>">
          <%= link_to "People", people_path %>
        </li>
        <li class="<%= 'active' if current_page?(businesses_path) %>">
          <%= link_to "Businesses", businesses_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroPolymorphic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>	
</div>


</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control", placeholder: "Enter a First Name" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Enter a Last Name" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/people/edit.html.erb
<h1>Editing <%= @person.name %></h1>
<%= render "form" %>

app/views/people/index.html.erb
<h1>People</h1>
<div class="well">
<%= link_to "New Person", new_person_path, class: "btn btn-primary" %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Interactions</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @people.count == 0 %>
      <tr>
        <td colspan="3">
          No people found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @people.each do |person| %>
        <tr>
          <td><%= link_to "#{person.first_name} #{person.last_name}", person %></td>
          <td><%= person.interactions.count %></td>
          <td>
            <%= link_to "Edit", edit_person_path(person), class: "btn btn-default" %>

            <%= link_to "Delete", person_path(person), 
            method: :delete, 
            data: { confirm: 'Are You Sure'},
            class: "btn btn-danger" %>
            
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>Create a New Person</h1>
<%= render "form" %>

app/views/people/show.html.erb
<h1><%= "#{@person.first_name} #{@person.last_name}" %></h1>
<hr />
<h3>Interactions</h3>
<div class="well">
  <%= link_to "New Interaction", new_person_interaction_path(@person), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Interactive Type</th>
      <th>Created On</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% if @person.interactions.count > 0 %>
    <% @person.interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.description %></td>
        <td><%= interaction.interactive_type %></td>
        <td><%= time_ago_in_words interaction.created_at %> ago</td>
        <td>

        <%= link_to "Edit", edit_person_interaction_path(@person, interaction), 
        class: "btn btn-default" %>

        <%= link_to person_interaction_path(@person, interaction), 
            method: :delete, 
            data: { confirm: "You sure?" }, 
            class: "btn btn-danger" do %>
                Delete
        <% end %>

        </td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="4">No interactions found for this person.  Click the 'New Interaction' button to create a new interaction.</td>
    </tr>
  <% end %>
</table>